### ISSUE TITLE
/ppwb command does not exist

### ISSUE THREAD

**Issue by drjawa** [Civcraft/PrisonPearl#50] opened 2015-05-30 06:24 UTC
Thank you to greenble for trying to test. Command does not seem to run or is an OP only command?

**Comment by ProgrammerDan** [comment] 2015-05-30 06:25
It should be OP only, based config.

**Comment by drjawa** [comment] 2015-05-30 06:27
I am OP'd, but can't seem to run the command. 

command does not exist.

**Comment by BlackXnt** [comment] 2015-05-30 08:25
Try this build: http://civcraft.co:8080/job/PrisonPearl-master/77/. I forgot to add the updated plugin.yml in the first pull.

**Comment by ttk2** [comment] 2015-05-30 13:21
does this pull the info from WB or from the config?

**Comment by BlackXnt** [comment] 2015-05-30 13:50
The calculation of when a pearl is outside of world border? From world border.

**Comment by ttk2** [comment] 2015-05-30 13:56
ok new build will be on Civtest in a minute.

**Comment by BlackXnt** [comment] 2015-05-30 13:59
Ok can you add me permissions to use tp, use the new command and if you can even bypass world border?

**Comment by ttk2** [comment] 2015-05-30 13:59
on civtest.

**Comment by ttk2** [comment] 2015-05-30 14:01
opped you.

**Comment by ttk2** [comment] 2015-05-30 14:02
2015-05-30 10:02:00 [INFO] Dr_Jawa issued server command: /ppwb
2015-05-30 10:02:00 [ERROR] null
org.bukkit.command.CommandException: Unhandled exception executing command
'ppwb' in plugin PrisonPearl v2.4.0
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46)
~[spigot.jar:git-Spigot-1d14d5f-7722428]
        at
org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
~[spigot.jar:git-Spigot-1d14d5f-7722428]
        at
org.bukkit.craftbukkit.v1_8_R2.CraftServer.dispatchCommand(CraftServer.java:646)
~[spigot.jar:git-Spigot-1d14d5f-7722428]
        at
net.minecraft.server.v1_8_R2.PlayerConnection.handleCommand(PlayerConnection.java:1139)
[spigot.jar:git-Spigot-1d14d5f-7722428]
        at
net.minecraft.server.v1_8_R2.PlayerConnection.a(PlayerConnection.java:974)
[spigot.jar:git-Spigot-1d14d5f-7722428]
        at
net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:45)
[spigot.jar:git-Spigot-1d14d5f-7722428]
        at
net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:1)
[spigot.jar:git-Spigot-1d14d5f-7722428]
        at
net.minecraft.server.v1_8_R2.PlayerConnectionUtils$1.run(SourceFile:13)
[spigot.jar:git-Spigot-1d14d5f-7722428]
        at
java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[?:1.8.0_45-internal]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[?:1.8.0_45-internal]
        at net.minecraft.server.v1_8_R2.SystemUtils.a(SourceFile:60)
[spigot.jar:git-Spigot-1d14d5f-7722428]
        at
net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:710)
[spigot.jar:git-Spigot-1d14d5f-7722428]
        at
net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368)
[spigot.jar:git-Spigot-1d14d5f-7722428]
        at
net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651)
[spigot.jar:git-Spigot-1d14d5f-7722428]
        at
net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554)
[spigot.jar:git-Spigot-1d14d5f-7722428]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45-internal]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
        at
com.untamedears.PrisonPearl.PrisonPearlCommands.WhiteListedLocations(PrisonPearlCommands.java:244)
~[?:?]
        at
com.untamedears.PrisonPearl.PrisonPearlCommands.onCommand(PrisonPearlCommands.java:234)
~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
~[spigot.jar:git-Spigot-1d14d5f-7722428]
        ... 15 more


boom that was fast.

**Comment by BlackXnt** [comment] 2015-05-30 14:06
Ok this is a 10 seconds fix. can you restart the server?

**Comment by ttk2** [comment] 2015-05-30 14:12
restarted.

**Comment by BlackXnt** [comment] 2015-05-30 14:33
Ok there is only one small problem: When you take out a pearl from a chest that is on the whitelist and you are standing outside of WB you will still get the message that the pearl will be released on restart(Only when you take the pearl from a chest not when you put the pearl in the chest). I will fix it later and make a pull with the fix for the exception.

**Comment by ttk2** [comment] 2015-05-30 15:02
thanks, keep me updated and let me know if you need anything.

**Comment by BlackXnt** [comment] 2015-05-30 21:58
https://github.com/Civcraft/PrisonPearl/pull/51

**Comment by BlackXnt** [comment] 2015-06-02 00:14
@ttk2 Me and MtFlushmore confirmed the changes are working yesterday. This is ready to go live.

**Comment by ttk2** [comment] 2015-06-02 00:40
good, going up tomorrow, thanks for the testing and coding! What do yall
want to tackle next?

**Comment by BlackXnt** [comment] 2015-06-02 00:46
I am going to try working on MusterCull this weekend.

**Comment by ttk2** [comment] 2015-06-02 01:30
sounds cool, keep me in the loop

**Comment by rourke750** [comment] 2015-06-04 01:03
Fixed?

**Comment by ttk2** [comment] 2015-06-04 01:14
think so

**Closed** 2015-06-04 01:15 UTC
Labels: bug, P3 - Nice to have
